#!/usr/bin/env php
<?php

foreach ([__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php'] as $file) {
    if (file_exists($file)) {
        /** @noinspection PhpIncludeInspection */
        require $file;
        break;
    }
}

$app = new \Symfony\Component\Console\Application('TYPO3 Surf', '1.0.0');
$app->add(new \TYPO3\Surf\Command\ReleaseCommand());
$app->run();
