name: Code Coverage

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    code_coverage:
        runs-on: ubuntu-latest
        env:
            COMPOSER_CACHE_DIR: ${{ github.workspace }}/.cache/composer
        steps:
            -   uses: actions/checkout@v2.0.0
            -   uses: actions/cache@v1
                with:
                    path: ${{ github.workspace }}/.cache
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-composer-
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none

            -   run: composer install --no-progress

            -   run: |
                    phpdbg -qrr -d memory_limit=-1 vendor/bin/phpunit --coverage-clover build/logs/clover.xml
                    # Coveralls.io
                    wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
                    php php-coveralls.phar --verbose
                env:
                    COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
