name: Static Analysis

on:
  pull_request: null
  push:
    branches:
      - main

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none

      - uses: ramsey/composer-install@v3

      - run: vendor/bin/phpstan analyse --ansi
