name: Static Analysis

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    phpstan:
        runs-on: ubuntu-latest
        env:
            COMPOSER_CACHE_DIR: ${{ github.workspace }}/.cache/composer
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/cache@v1
                with:
                    path: ${{ github.workspace }}/.cache
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-composer-
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none
            -   run: composer install --no-progress
            -   run: composer phpstan
