name: Build Phar and create new Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  tagged-release:
    name: Tagged Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer Dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Box global
        run: composer global require "humbug/box:^3.8" --no-ansi --no-interaction --no-progress --classmap-authoritative

      - name: Install Composer Dependencies
        run: composer install --no-ansi --no-interaction --no-dev --no-progress --classmap-authoritative

      - name: Compile Phar with Box
        run: box compile

      - name: Run surf.phar once
        run: release/surf.phar --version

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV  # tag x.y.z will become "TYPO3 Surf x.y.z"

      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: TYPO3 Surf ${{ env.RELEASE_VERSION }}
          files: |
            release/surf.phar
